### ISSUE TITLE
Error: XMLHttpRequest error.

### ISSUE THREAD

**Issue by yosef406** [lejard-h/google_maps_webservice#87]
Hello,
working in flutter web,
added requirements
![image](https://user-images.githubusercontent.com/63299984/98718562-43d50580-2397-11eb-80d4-98e9a7e39a01.png)
![image](https://user-images.githubusercontent.com/63299984/98719106-015ff880-2398-11eb-9f3f-47e560a90520.png)
![image](https://user-images.githubusercontent.com/63299984/98719143-0de45100-2398-11eb-8b01-16c08913b728.png)
when using searchNearbyWithRadius() or autocomplete() i get an error 
![image](https://user-images.githubusercontent.com/63299984/98719337-4ab04800-2398-11eb-9389-afb24cd250bc.png)

![image](https://user-images.githubusercontent.com/63299984/98719377-5865cd80-2398-11eb-87b2-c33c403ae678.png)
this one shows me no errors.

![image](https://user-images.githubusercontent.com/63299984/98719466-77645f80-2398-11eb-91d3-c89c88789c60.png)
this one shows me the error mentioned above.
please help.

**Comment by yosef406** [comment]
ok so the first problem was solved, (i think)
but now i am stuck with a new problem,

**Comment by yosef406** [comment]
ok so the first problem was solved, i under stood that the problem is a cors problem and has sumthing to do with security
the solution was to add a proxy to the "baseUrl" section 
![image](https://user-images.githubusercontent.com/63299984/98859460-e8744780-246a-11eb-8623-544547b4031b.png)

but now im stuck with a new problem, 
![image](https://user-images.githubusercontent.com/63299984/98859570-1194d800-246b-11eb-962d-0503987970bb.png)
the same code was used but with a proxy,
to what i understand this new problem is caused because the google servers respond with Jason file but the flutter app is not reading it right, i maybe wrong.

**Comment by fikrirazzaq** [comment]
> ok so the first problem was solved, i under stood that the problem is a cors problem and has sumthing to do with security
> the solution was to add a proxy to the "baseUrl" section
> ![image](https://user-images.githubusercontent.com/63299984/98859460-e8744780-246a-11eb-8623-544547b4031b.png)
> 
> but now im stuck with a new problem,
> ![image](https://user-images.githubusercontent.com/63299984/98859570-1194d800-246b-11eb-962d-0503987970bb.png)
> the same code was used but with a proxy,
> to what i understand this new problem is caused because the google servers respond with Jason file but the flutter app is not reading it right, i maybe wrong.

Try this solution https://github.com/lejard-h/google_maps_webservice/issues/70#issuecomment-636919093

It works for me.

**Comment by eqrakhattak** [comment]
> > ok so the first problem was solved, i under stood that the problem is a cors problem and has sumthing to do with security
> > the solution was to add a proxy to the "baseUrl" section
> > ![image](https://user-images.githubusercontent.com/63299984/98859460-e8744780-246a-11eb-8623-544547b4031b.png)
> > but now im stuck with a new problem,
> > ![image](https://user-images.githubusercontent.com/63299984/98859570-1194d800-246b-11eb-962d-0503987970bb.png)
> > the same code was used but with a proxy,
> > to what i understand this new problem is caused because the google servers respond with Jason file but the flutter app is not reading it right, i maybe wrong.
> 
> Try this solution [#70 (comment)](https://github.com/lejard-h/google_maps_webservice/issues/70#issuecomment-636919093)
> 
> It works for me.

I tried using this one but I'm still getting the same thing as above:

![image](https://user-images.githubusercontent.com/60545262/120108789-21160d00-c180-11eb-904a-cee19d95446f.png)

any solution?

**Comment by eqrakhattak** [comment]
@lejard-h @fikrirazzaq I tried that solution and still gives me this:

![image](https://user-images.githubusercontent.com/60545262/120108855-64707b80-c180-11eb-8b83-8973b0c44e6f.png)

Any solution?

**Comment by binnicordova** [comment]
Same problem here :c
